config/routes.rb
Rails.application.routes.draw do
  root to: 'tw_clones#top'

  resources :tw_clones do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tw_clone.rb
class TwClone < ApplicationRecord
  validates :content, length: {minimum: 1, maximum: 140, message: "空では登録できません。１４０文字以内で入力してください"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tw_clones_controller.rb
class TwClonesController < ApplicationController
  before_action :set_tw, only: [:edit, :update, :destroy]

  def top
  end

  def index
    @twclones = TwClone.all
  end

  def new
    if params[:back]
      @twclone = TwClone.new(tw_params)
    else
      @twclone = TwClone.new
    end
  end

  def create
    @twclone = TwClone.new(tw_params)
    if @twclone.save
      redirect_to new_tw_clone_path, notice: "つぶやきを投稿しました！！"
    else
      render 'new'
    end
  end

  def edit
  end
  def update

    if @twclone.update(tw_params)
      redirect_to tw_clones_path, notice: "つぶやきを編集しました！！"
    else
      render 'edit'
    end
  end

  def destroy
    @twclone.destroy
    redirect_to tw_clones_path, notice:"つぶやきを削除しました！！"
  end

  def confirm
    @twclone = TwClone.new(tw_params)
    render :new if @twclone.invalid?
  end


  private
  def tw_params
    params.require(:tw_clone).permit(:content)
  end
  def set_tw
    @twclone = TwClone.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tw_clones_helper.rb
module TwClonesHelper
  def choose_new_or_edit
    if action_name =='new' || action_name == 'confirm'
      confirm_tw_clones_path
    elsif action_name == 'edit'
      tw_clone_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwiClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
                <span class="sr-only">header</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">
                ツイッタークローン
              </a>
            </div>
            <div id="gnavi" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <!-- <li><%= link_to "ホーム", root_path %></li>
                <li><%= link_to "新しいつぶやき", new_tw_clone_path %></li>
                <li><%= link_to "つぶやき一覧", tw_clones_path %></li> -->

                <li class="top_img"><%= link_to image_tag('HOME_GREY.png'), root_path %></li>
                <li class="top_img"><%= link_to image_tag('message_gray.png'), new_tw_clone_path  %></li>
                <li class="top_img"><%= link_to image_tag('moment_glay.png'), tw_clones_path %></li>
              </ul>
            </div>
          </div>
        </nav>

      </header>
    <%= yield %>
    </div>

  <footer class="footer">
    <div class="container">
      <p class="text-muted">© 2017-2018 Copyright Kensuke Matsumoto</p>
    </div>
  </footer>
  </body>
</html>

app/views/tw_clones/_form.html.erb
<div class="article">
  <%= form_with(model: @twclone,url: choose_new_or_edit, local: true) do |form| %>
    <% if @twclone.errors.any? %>
      <div class="bg-danger" id="error_explanation">
        <h2><%= @twclone.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @twclone.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="tw_new">
      つぶやき：
      <%= form.text_field :content %>
    </div>
    <%= form.submit "登録" %>
  <% end %>
  <%= link_to "つぶやき一覧に戻る", tw_clones_path %>
</div>

app/views/tw_clones/cofirm.html.erb
<h3>この内容でつぶやきます</h3>

<%= form_with(model: @twclone, url: tw_clones_path,local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= @twclone.content %>
  <%= form.submit "登録する" %>
<% end %>

<%= form_with(model: @twclone, url: new_twclone_path,local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/tw_clones/confirm.html.erb
<h3>この内容でつぶやきます</h3>

<%= form_with(model: @twclone, url: tw_clones_path,local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= @twclone.content %><br>
  <%= form.submit "登録する" %>
<% end %>

<%= form_with(model: @twclone, url: new_tw_clone_path,local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/tw_clones/edit.html.erb
<div class="article">
  <h1>つぶやき編集画面</h1>

  <%= render 'form' %>
</div>

app/views/tw_clones/index.html.erb
<section class="main-header">
  <%= image_tag 'title.jpg' %>
</section>
<div class="article">
  <p id="notice"><%= notice %></p>

  <h1>つぶやき一覧</h1>

  <table class="tweet_list">
      <% @twclones.each do |tw| %>
        <tr>
          <td colspan="2" class="tweet_content"><%= tw.content %></td>
        </tr>
        <tr>
          <td><%= link_to 'つぶやきを編集する', edit_tw_clone_path(tw.id), type: "button", class: "btn btn-info" %></td>
          <td><%= link_to 'つぶやきを破棄する', tw_clone_path(tw.id), method: :delete, data: { confirm: "本当に削除してよいですか" },type: "button",class: "btn btn-danger" %></td>
        </tr>
      <% end %>
  </table>

  <br>

  <%= link_to 'ツイート', new_tw_clone_path,type:"button",class:"btn btn-primary btn-lg" %>
</div>

app/views/tw_clones/new.html.erb
<div class="article">
  <h1>いまどうしてる?</h1>

  <%= render 'form' %>
</div>

app/views/tw_clones/top.html.erb
<section class="main-header">
  <%= image_tag 'title.jpg' %>
</section>
<div class="container">
  <section class="article">
    <h1>トップ画面</h1>
    <P>このアプリはブログアプリです。</P>
    <p>ブログの新規作成とブログの一覧画面から編集削除などができます</p>
  </section>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4 grid-img">

        <%= link_to image_tag('HOME_GREY.png'), root_path %>

    </div>
    <div class="col-md-4 grid-img">

        <%= link_to image_tag('message_gray.png'), new_tw_clone_path  %>

    </div>
    <div class="col-md-4 grid-img">

        <%= link_to image_tag('moment_glay.png'), tw_clones_path %>

    </div>
  </div>
</div>